// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://datjhuldmypydbvbfalf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhdGpodWxkbXlweWRidmJmYWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDg5MTksImV4cCI6MjA2NzEyNDkxOX0.GW6dGMYWD1MKZJ1VTagD_HeKMnJbuYqrY7M1_v55gLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});